"""Adapt splat assembly to Ps2EeAs, retaining the RAC1 measured VU/float fixes.

RAC2 validation is the exact byte gate in build.py, not the RAC1 measurements.
Only generated local assembly is processed; this script includes no retail code.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
LABEL_MACROS = {"glabel", "alabel", "dlabel", "jlabel", "ehlabel"}
NOOP_MACROS = {"endlabel", "enddlabel", "nonmatching"}

RE_INCLUDE = re.compile(r'^\s*\.include\s+"macro\.inc"\s*$')
RE_CONSTANTE = re.compile(r"^D_[0-9A-F]+$")
RE_VADDA = re.compile(
    r"^(?P<tete>.*?\bvadda(?:\.\w+)?\s+\$ACC\s*,\s*)"
    r"(?P<a>\$vf\d+)(?P<virg>\s*,\s*)(?P<b>\$vf\d+)"
    r"(?P<queue>\s*(?:/\*.*)?)$")


def corrige_vadda(ligne: str) -> str:
    """Swap the two source registers of a `vadda` (see RE_VADDA).

    Apply to EVERY input line, including lines prefixed with a comment
    `/* offset VRAM bytes */`: this is the format emitted by splat.
    """
    match = RE_VADDA.match(ligne)
    if not match:
        return ligne
    return f"{match['tete']}{match['b']}{match['virg']}{match['a']}{match['queue']}"
RE_FLOAT_MOINS_ZERO = re.compile(
    r"^(?P<tete>.*?)\.float\s+-0(?:\.0+)?(?P<queue>\s*(?:/\*.*)?)$")


def corrige_float_moins_zero(ligne: str) -> str:
    """`.float -0` -> `.word 0x80000000` (see RE_FLOAT_MOINS_ZERO)."""
    match = RE_FLOAT_MOINS_ZERO.match(ligne)
    if not match:
        return ligne
    return f"{match['tete']}.word 0x80000000{match['queue']}"


def corrige_encodage(ligne: str) -> str:
    """Measured DIALECT corrections, applied to every input line.

    Use one entry point so that each newly measured correction has
    a single place to be added.
    """
    return corrige_float_moins_zero(corrige_vadda(ligne))


def expand_line(line: str, local: bool = False,
                vus: set[str] | None = None) -> list[str]:
    """Translate a line; return the output lines (empty means removed).

    `local` keeps symbols LOCAL (no .globl).
    `vus`   tracks symbols already declared IN THIS FILE.

    WHY LABELS ARE DEDUPLICATED
    -------------------------
    splat emits multiple labels for one address: a function may have
    both a `glabel` AND an `alabel` (another entry point), while data may have
    a `dlabel` AND a `jlabel` (jump target). Expanding these macros
    produces the same label twice in one file, and
    the assembler rejects it -- or the linker reports "multiple definition" with
    both references in the SAME object. This distinguishes the case
    from a genuine conflict between two files.
    """
    if vus is None:
        vus = set()
    if RE_INCLUDE.match(line):
        return []

    stripped = line.strip()
    if not stripped or stripped.startswith(("#", "/*")):
        return [line]

    parts = stripped.split(None, 1)
    mot = parts[0] if parts else ""
    arg = parts[1].strip() if len(parts) > 1 else ""

    if mot in NOOP_MACROS:
        return []

    if mot in LABEL_MACROS:
        if not arg:
            return [line]
        nom = arg.split(",")[0].strip()
        if RE_CONSTANTE.match(nom):
            return []

        if nom in vus:
            return []          # already declared in this file: skip it
        vus.add(nom)
        return [f"{nom}:"] if local else [f".globl {nom}", f"{nom}:"]

    return [line]


def process(src: Path, dst: Path) -> tuple[int, int]:
    """Translate a file. Return (lines read, lines written)."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    PREFIXES_NON_CHARGEES = (
        "DVP_overlay_",     # 43 overlays
        "DVP_ovlytab",      # overlay table
        "DVP_ovlystrtab",   # overlay strings
        "shstrtab",         # section-name table
    )
    local = src.name.startswith(PREFIXES_NON_CHARGEES)

    lignes_in = src.read_text(encoding="utf-8", errors="replace").splitlines()
    lignes_out: list[str] = []
    vus: set[str] = set()
    for ligne in lignes_in:
        lignes_out.extend(expand_line(corrige_encodage(ligne), local=local, vus=vus))
    dst.write_text("\n".join(lignes_out) + "\n", encoding="ascii", errors="replace")
    return len(lignes_in), len(lignes_out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Translate splat output to the Ps2EeAs dialect.")
    ap.add_argument("--src", required=True, type=Path, help="input tree generated by splat")
    ap.add_argument("--dst", required=True, type=Path, help="output tree")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args(argv)

    if not args.src.is_dir():
        print(f"ERROR: {args.src} is not a directory", file=sys.stderr)
        return 1

    fichiers = sorted(args.src.rglob("*.s"))
    if not fichiers:
        print(f"ERROR: no .s files under {args.src}", file=sys.stderr)
        return 1

    total_in = total_out = 0
    for source_file in fichiers:
        rel = source_file.relative_to(args.src)
        n_in, n_out = process(source_file, args.dst / rel)
        total_in += n_in
        total_out += n_out
        if args.verbose:
            print(f"  {rel}  {n_in} -> {n_out} lines")

    print(f"OK  {len(fichiers)} files translated")
    print(f"    {args.src}  ->  {args.dst}")
    print(f"    {total_in:,} lines read, {total_out:,} written".replace(",", " "))
    print(f"    removed: {total_in - total_out} (end macros and markers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


